### ISSUE TITLE
[BUG] Just importing framer-motion breaks production builds with Snowpack

### ISSUE THREAD

**Issue by bard** [framer/motion#1224]
**2. Describe the bug**

Projects that use framer-motion cannot be bundled with Snowpack:

```sh
$ snowpack build
[09:25:52] [snowpack] ! building files...
[09:25:52] [snowpack] ✔ files built. [0.06s]
[09:25:52] [snowpack] ! building dependencies...
[09:25:55] [@snowpack/plugin-typescript] Command completed.
[09:25:55] [snowpack] ✔ dependencies built. [3.14s]
[09:25:55] [snowpack] ! writing to disk...
[09:25:55] [snowpack] ✔ write complete. [0.01s]
[09:25:55] [snowpack] ! optimizing build...
[09:25:55] [snowpack] rimrafSafe(): /tmp/test/node_modules/@emotion/memoize/dist/memoize.browser.cjs.js outside of buildOptions.out /tmp/test/build
[09:25:55] [snowpack] Error: rimrafSafe(): /tmp/test/node_modules/@emotion/memoize/dist/memoize.browser.cjs.js outside of buildOptions.out /tmp/test/build
    at Object.deleteFromBuildSafe (/tmp/test/node_modules/snowpack/lib/cjs/util.js:76:15)
    at Object.runBuiltInOptimize (/tmp/test/node_modules/snowpack/lib/cjs/build/optimize.js:419:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.optimize (/tmp/test/node_modules/snowpack/lib/cjs/build/process.js:299:9)
    at async build (/tmp/test/node_modules/snowpack/lib/cjs/commands/build.js:18:5)
    at async Object.command (/tmp/test/node_modules/snowpack/lib/cjs/commands/build.js:35:9)
    at async cli (/tmp/test/node_modules/snowpack/lib/cjs/index.js:174:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Perhaps related and/or introduced by https://github.com/framer/motion/pull/60. Related: https://github.com/snowpackjs/snowpack/issues/3403

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Due to the nature of the problem, repro provided as repository instead: https://github.com/bard/framer-motion-snowpack-build-problem-repro (based on standard https://www.npmjs.com/package/create-snowpack-app plus minimal patch just to import framer motion).

**4. Steps to reproduce**

1. `git clone https://github.com/bard/framer-motion-snowpack-build-problem-repro`
2. `cd framer-motion-snowpack-build-problem-repro`
3. `yarn build`

**5. Expected behavior**

Project builds.

**Comment by sachaw** [comment]
Also experiencing this, and have not sound any workaround to get any snowpack project with framer-motion to build.

**Comment by mattgperry** [comment]
I've given this a go with the latest versions of everything and it worked for me. This is something I expect to have changed with the release of 5 as well because we moved to esm modules.
