### ISSUE TITLE
[BUG] Error in package.json exports makes Next.js to error out | framer-motion@5.4.2

### ISSUE THREAD

**Issue by PabloSzx** [framer/motion#1384]
**Describe the bug**

framer-motion@4.5.2 has wrong exports:

![Screenshot from 2021-12-07 16-50-45](https://user-images.githubusercontent.com/8672915/145096600-69e8096f-488f-4610-9d8c-0d9f789669cf.png)

When building with Next.js, it errors out:

```
> Build error occurred
Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/cjs/index.js" defined in the package config .../node_modules/framer-motion/package.json; targets must start with "./"
    at new NodeError (internal/errors.js:322:7)
    at throwInvalidPackageTarget (internal/modules/esm/resolve.js:341:9)
    at resolvePackageTargetString (internal/modules/esm/resolve.js:369:5)
    at resolvePackageTarget (internal/modules/esm/resolve.js:406:12)
    at resolvePackageTarget (internal/modules/esm/resolve.js:452:26)
    at packageExportsResolve (internal/modules/esm/resolve.js:507:22)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27) {
  type: 'NodeError',
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
info  - Collecting page data . ELIFECYCLE  Command failed with exit code 1.
```

Created this small reproduction repo using Next.js and forcing to use commonjs: https://github.com/PabloSzx/framer-motion-cjs-next-bug, which will use the wrong path

**Expected behavior**

To not error out

**Environment details**

Node.js v14.18.2

**Comment by mattgperry** [comment]
Fixed in 5.4.3
