### ISSUE TITLE
[BUG] Build with vite crashes ( 'MeasureLayout' is not exported by node_modules\framer-motion\dist\es\motion\features\layout\MeasureLayout.mjs)

### ISSUE THREAD

**Issue by jacobgavin** [framer/motion#1394]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Can't build vite project when using framer-motion `motion.div` with react. Can however run project fine, just build doesn't work.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Unfortunately I couldn't set up a replicated codesandbox/stackblitz environment since it's a build problem. 

**5. Expected behavior**

Build succeeds. It works to run with vite but not to build.

**6. Video or screenshots**
Error log:
```
vite v2.6.14 building for staging...
✓ 13249 modules transformed.
'MeasureLayout' is not exported by node_modules\framer-motion\dist\es\motion\features\layout\MeasureLayout.mjs, imported by node_modules\framer-motion\dist\es\motion\features\layout\index.mjs
file: C:/repos/webapp/node_modules/framer-motion/dist/es/motion/features/layout/index.mjs:1:9
1: import { MeasureLayout } from './MeasureLayout.mjs';
            ^
2: 
3: var layoutFeatures = {
error during build:
Error: 'MeasureLayout' is not exported by node_modules\framer-motion\dist\es\motion\features\layout\MeasureLayout.mjs, imported by node_modules\framer-motion\dist\es\motion\features\layout\index.mjs
    at error (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:158:30)
    at Module.error (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:12382:16)
    at Module.traceVariable (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:12767:29)
    at ModuleScope.findVariable (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:11559:39)
    at Identifier.bind (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:6419:40)
    at Property.bind (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:5025:23)
    at ObjectExpression.bind (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:5021:31)
    at VariableDeclarator.bind (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:5025:23)
    at VariableDeclaration.bind (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:5021:31)
    at Program.bind (C:\repos\webapp\node_modules\rollup\dist\shared\rollup.js:5021:31)
```

**7. Environment details**

Windows 10, VSCode, vite.

**Comment by esmevane** [comment]
I've reproduced this as well. Editing the `layout/index.mjs` file to this "worked", but didn't illuminate (to me) what the issue is:

```js
import * as ML from './MeasureLayout.mjs';

var layoutFeatures = {
    measureLayout: ML.MeasureLayout,
};

export { layoutFeatures };
```

**Comment by mattgperry** [comment]
Please reopen/create a new ticket with a Github repo I can fork to check this out if CodeSandbox is not possible.
