### ISSUE TITLE
[BUG] Reorder.Group: creating snapshot of component with jest fails with TypeError in use-motion-value

### ISSUE THREAD

**Issue by kgkg** [framer/motion#1397]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When trying to generate storybook snapshot of component with just basic usage of Reorder.Group and Reorder.Item it fails with error:

```ts
$ jest -u
 FAIL  tests/storyshots.test.js (5.811 s)
  Storyshots
    components/ReorderTiles
      ✕ Default (87 ms)

  ● Storyshots › components/ReorderTiles › Default

    TypeError: Cannot read property 'addEventListener' of undefined

      at addDomEvent (node_modules/framer-motion/dist/cjs/use-motion-value-3615b5bb.js:3233:12)
      at Object.addPointerEvent (node_modules/framer-motion/dist/cjs/use-motion-value-3615b5bb.js:3367:12)
      at VisualElementDragControls.Object.<anonymous>.VisualElementDragControls.addListeners (node_modules/framer-motion/dist/cjs/index.js:1511:50)
      at node_modules/framer-motion/dist/cjs/index.js:1600:55
      at invokePassiveEffectCreate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14504:20)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11391:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11440:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14591:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
      at flushPassiveEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14464:14)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13380:3)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
      at flushSyncCallbackQueueImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2532:9)
      at flushSyncCallbackQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2519:3)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13004:9)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16454:3)
      at Object.unmount (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17211:7)
      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:28:22)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:43:44
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Reproductible only from command line - see below.

**4. Steps to reproduce**

1. clone repository https://github.com/kgkg/framer-bug-repro
2. `yarn install`
3. `jest -u`
4. You should see the error above. 

Additional info:
- storyshot files are created anyway 
- but running `jest -u` will trigger this error again and running `jest` will fail because of it.
- this code works without any issues in storybook (can be run with `npm run storybook`)
- removing `Reorder.Item` in `src/components/ReorderTiles/ReorderTiles.tsx` and replacing it with `<div>`s makes snapshot update passing without any issues.

**5. Expected behavior**

Snapshot should build and test should pass.

**6. Video or screenshots**

**7. Environment details**

MacOSx 12.1
node 16.2
yarn 1.22.17
framer-motion: 5.5.5 (newest atm)
Storybook 6.4.9 (newest atm)

**Comment by mattgperry** [comment]
I've had a play, there's a different error in the latest version with a stack trace that ends on react-test-renderer. Even so I'm marking this as wontfix - we do SSR, E2E and live Jest testing, I don't think this is a bug on our side.
