### ISSUE TITLE
[BUG] Using `MotionCanvas` from "framer-motion-3d" instead of `Canvas` from "@react-three/fiber" causes `@react-three/fiber` components to throw `Uncaught *COMPONENT* is not part of the THREE namespace! Did you forget to extend? ` errors at runtime

### ISSUE THREAD

**Issue by hood** [framer/motion#1635]
Using `MotionCanvas` from `framer-motion-3d` instead of `Canvas` from `@react-three/fiber` causes wrapped `@react-three/fiber` components to throw `Uncaught *COMPONENT* is not part of the THREE namespace! Did you forget to extend? ` errors at runtime.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/busy-nightingale-9w4v6t?file=/src/App.tsx

**4. Steps to reproduce**
Run the project

**5. Expected behavior**
`MotionCanvas` to be interchangeable with `Canvas`

**6. Video or screenshots**
//

**7. Environment details**
`framer-motion-3d` version: 6.5.1 
`@react-three/fiber` version: 8.2.2

**Comment by hood** [comment]
UPDATE: The error itself goes away if I pin `@react-three/fiber` to v7, but then I get the following error at runtime:
```
TypeError: mergeRefs is not a function
    at CanvasComponent (file:///home/userName/Documents/project1/node_modules/framer-motion-3d/dist/es/components/MotionCanvas.mjs:101:46)
    at renderWithHooks (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5842:18)
    at renderElement (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderSuspenseBoundary (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5591:5)
    at renderElement (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5994:11)
    at renderNodeDestructiveImpl (/home/userName/Documents/project1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
```

**Comment by hood** [comment]
Just trying this new version. I'm experiencing this same issue under the following versions:
```
    "@react-three/drei": "^9.28.3",
    "@react-three/fiber": "^8.7.2",
    "@react-three/flex": "^1.0.0",
    "framer-motion": "^7.3.2",
    "framer-motion-3d": "^7.3.2",
    "three": "^0.144.0",
```

**Comment by willnida1** [comment]
was this ever solved? Running into the same issue rn

**Comment by lakindu62** [comment]
Guys I have the same issue when using  MotionCanvas to animate LayoutCamera , as it throws a namespace error in React , anyone has any idea on how to fix this?

**Comment by twosaturdayscode** [comment]
See this guys: https://github.com/framer/motion/issues/2074#issuecomment-1724813108
