### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HappyMajor** [framer/motion#1718]
When I try to build my project in CloudFlare, the following build error appears:

```
> Build error occurred
--
09:37:54.319 | file:///opt/buildhome/repo/node_modules/framer-motion/dist/es/context/MotionConfigContext.mjs:1
09:37:54.319 | import { createContext } from 'react';
09:37:54.320 | ^^^^^^^^^^^^^
09:37:54.320 | SyntaxError: The requested module 'react' does not provide an export named 'createContext'
09:37:54.320 | at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
09:37:54.320 | at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
09:37:54.320 | at async Loader.import (internal/modules/esm/loader.js:179:24) {
09:37:54.321 | type: 'SyntaxError'
09:37:54.321 | }
```

my dependencies:

```+-- @emotion/react@11.10.0
+-- @emotion/styled@11.10.0
+-- @mui/material@5.10.0
+-- eslint-config-next@12.2.3
+-- eslint@8.20.0
+-- framer-motion@7.5.0
+-- next@12.2.3
+-- react-cookie-consent@8.0.1
+-- react-css-collapse@4.1.0
+-- react-dom@18.2.0
+-- react-media-hook@0.4.9
+-- react@18.2.0
`-- reactjs-popup@2.0.5```

**Comment by mattgperry** [comment]
Maybe related to https://github.com/vercel/next.js/discussions/34868 ?

**Comment by mattgperry** [comment]
Ah this person is also on Cloudflare - I'm going to close this as it looks like an issue between Next and Cloudflare more specifically and the linked issue will do a better job of tracking.
