### ISSUE TITLE
[BUG] scrapeMotionValuesFromProps is not defined in Next.JS 13 rendering process

### ISSUE THREAD

**Issue by HakkaOfDev** [framer/motion#1782]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

The error appears when I'm trying to render the page.

```
error - [rendering] [root of the dev server]/
  Error during SSR Rendering
  ReferenceError: scrapeMotionValuesFromProps is not defined
    at <unknown> (/node_modules/framer-motion/dist/es/render/html/config-motion.mjs:7:8)
    at Module.[project-with-next]/node_modules/framer-motion/dist/es/render/html/config-motion.mjs (ecmascript, ssr) (.next\server\app\chunks\ssr\_369ebe.js:45753:3)  
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:194096:21)
    at runModuleExecutionHooks (.next\server\app\chunks\ssr\_369ebe.js:194134:5)
    at instantiateModule (.next\server\app\chunks\ssr\_369ebe.js:194095:5)
    at getOrInstantiateModuleFromParent (.next\server\app\chunks\ssr\_369ebe.js:194176:12)
    at esmImport (.next\server\app\chunks\ssr\_369ebe.js:193905:20)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:44043:165)
    at Module.[project-with-next]/node_modules/framer-motion/dist/es/render/dom/utils/create-config.mjs (ecmascript, ssr) (.next\server\app\chunks\ssr\_369ebe.js:44062:3)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:194096:21)
    at runModuleExecutionHooks (.next\server\app\chunks\ssr\_369ebe.js:194134:5)
    at instantiateModule (.next\server\app\chunks\ssr\_369ebe.js:194095:5)
    at getOrInstantiateModuleFromParent (.next\server\app\chunks\ssr\_369ebe.js:194176:12)
    at esmImport (.next\server\app\chunks\ssr\_369ebe.js:193905:20)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:41166:173)
    at Module.[project-with-next]/node_modules/framer-motion/dist/es/render/dom/motion.mjs (ecmascript, ssr) (.next\server\app\chunks\ssr\_369ebe.js:41197:3)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:194096:21)
    at runModuleExecutionHooks (.next\server\app\chunks\ssr\_369ebe.js:194134:5)
    at instantiateModule (.next\server\app\chunks\ssr\_369ebe.js:194095:5)
    at getOrInstantiateModuleFromParent (.next\server\app\chunks\ssr\_369ebe.js:194176:12)
    at esmImport (.next\server\app\chunks\ssr\_369ebe.js:193905:20)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:41015:154)
    at Module.[project-with-next]/node_modules/framer-motion/dist/es/index.mjs (ecmascript, ssr) (.next\server\app\chunks\ssr\_369ebe.js:41157:3)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:194096:21)
    at runModuleExecutionHooks (.next\server\app\chunks\ssr\_369ebe.js:194134:5)
    at instantiateModule (.next\server\app\chunks\ssr\_369ebe.js:194095:5)
    at getOrInstantiateModuleFromParent (.next\server\app\chunks\ssr\_369ebe.js:194176:12)
    at esmImport (.next\server\app\chunks\ssr\_369ebe.js:193905:20)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:40421:136)
    at Module.[project-with-next]/node_modules/@chakra-ui/transition/dist/index.esm.js (ecmascript, ssr) (.next\server\app\chunks\ssr\_369ebe.js:40934:3)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:194096:21)
    at runModuleExecutionHooks (.next\server\app\chunks\ssr\_369ebe.js:194134:5)
    at instantiateModule (.next\server\app\chunks\ssr\_369ebe.js:194095:5)
    at getOrInstantiateModuleFromParent (.next\server\app\chunks\ssr\_369ebe.js:194176:12)
    at esmImport (.next\server\app\chunks\ssr\_369ebe.js:193905:20)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:75598:148)
    at Module.[project-with-next]/node_modules/@chakra-ui/accordion/dist/index.esm.js (ecmascript, ssr) (.next\server\app\chunks\ssr\_369ebe.js:75966:3)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:194096:21)
    at runModuleExecutionHooks (.next\server\app\chunks\ssr\_369ebe.js:194134:5)
    at instantiateModule (.next\server\app\chunks\ssr\_369ebe.js:194095:5)
    at getOrInstantiateModuleFromParent (.next\server\app\chunks\ssr\_369ebe.js:194176:12)
    at esmImport (.next\server\app\chunks\ssr\_369ebe.js:193905:20)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:25978:147)
    at Module.[project-with-next]/node_modules/@chakra-ui/react/dist/index.esm.js (ecmascript, ssr) (.next\server\app\chunks\ssr\_369ebe.js:26086:3)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:194096:21)
    at runModuleExecutionHooks (.next\server\app\chunks\ssr\_369ebe.js:194134:5)
    at instantiateModule (.next\server\app\chunks\ssr\_369ebe.js:194095:5)
    at getOrInstantiateModuleFromParent (.next\server\app\chunks\ssr\_369ebe.js:194176:12)
    at esmImport (.next\server\app\chunks\ssr\_369ebe.js:193905:20)
    at <unknown> (.next\server\app\chunks\ssr\_369ebe.js:1086:143)
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

I'll create soon.

**4. Steps to reproduce**

1. Go to '/'
2. See error

**5. Expected behavior**

Just render the page.

**6. Video or screenshots**

![image](https://user-images.githubusercontent.com/30605074/203012117-645afd70-ea4c-4ffc-9f93-6b2fa240c2bc.png)

**7. Environment details**

Brave Latest / NextJS 13.0.4 / TurboPack activated / Framer-Motion 7.6.7

**Comment by mpereira** [comment]
I'm seeing this too. Did you get it resolved @HakkaOfDev?

**Comment by mpereira** [comment]
No worries!
