### ISSUE TITLE
[BUG] Inactionable warning when using LazyMotion + Reorder

### ISSUE THREAD

**Issue by lourd** [framer/motion#2094]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I'm using `LazyMotion` with `strict` enabled on my whole app, but `Reorder` on a single page. This is printing a warning for the Reorder Group and the Reorder Item

I've read through the [PR that implemented the warning](https://github.com/framer/motion/pull/1931), and a warning is certainly better than an error :) but I would still like a way to suppress/intentionally ignore this warning for this part of the component tree. I've read and acknowledged the warning, but there's nothing I can do about it.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

1. Make a Next.js app with `<LazyMotion strict features={() => import('framer-motion').then(mod => mod.domMax)}>` wrapping the whole app
2. On one page, using the `Reorder.Group` + `Reorder.Item` components
3. See the warning logged to the console

**5. Expected behavior**

It seems to me like the Reorder components should use `m` under the hood and functionality should just break if the user hasn't set up `LazyMotion` correctly, or there should be some kind of `noWarn` prop that can be set. It feels like we're in a weird middleground with the current warning that you can't do anything about.

**6. Video or screenshots**

```
You have rendered a `motion` component within a `LazyMotion` component. This will break tree shaking. Import and render a `m` component instead. 
    at MotionComponent (webpack-internal:///../../node_modules/framer-motion/dist/es/motion/index.mjs:51:65)
    at ReorderGroup (webpack-internal:///../../node_modules/framer-motion/dist/es/components/Reorder/Group.mjs:20:25)
 
...

You have rendered a `motion` component within a `LazyMotion` component. This will break tree shaking. Import and render a `m` component instead. 
    at MotionComponent (webpack-internal:///../../node_modules/framer-motion/dist/es/motion/index.mjs:51:65)
    at ReorderItem (webpack-internal:///../../node_modules/framer-motion/dist/es/components/Reorder/Item.mjs:27:24)
 ```

**7. Environment details**

framer-motion@10.11.2

**Comment by xvivx999** [comment]
The re-enactment scenario is more complicated. I use the micro-qiankun front-end architecture. The main application will report this error when loading the sub-application. The sub-application uses LazyMotion and strict attributes.

**Comment by vucat12** [comment]
Any updates?
