### ISSUE TITLE
[BUG] `useAnimate` animation sequence is throwing TypeError

### ISSUE THREAD

**Issue by soosap** [framer/motion#2131]
I have an existing simple spinner component built in react-spring which I try to transition to framer-motion. It executes 2 individual animations in sequence and then infinitely repeats the entire sequence. I was not able to achieve that with the `motion` component. However, leveraging the `useAnimate` hook I was able to get it to work. However, when the component unmounts I get this error: 

```
Error
No valid element provided.
Call Stack
 invariant
  vendors-node_modules_framer-motion_dist_es_render_dom_motion_mjs.iframe.bundle.js:11399:19
 animateElements
  vendors-node_modules_framer-motion_dist_es_animation_hooks_use-animate_mjs.iframe.bundle.js:111:65
 scopedAnimate
  vendors-node_modules_framer-motion_dist_es_animation_hooks_use-animate_mjs.iframe.bundle.js:165:25
 animateCircle
  components-LoadingIndicator-stories-LoadingIndicator-theme-stories.iframe.bundle.js:221:13
 async animateCircle
  components-LoadingIndicator-stories-LoadingIndicator-theme-stories.iframe.bundle.js:242:7

```

This is how I do it:
```tsx
const [scope, animate] = useAnimate<SVGCircleElement>()
useEffect(() => {
    const animateCircle = async () => {
      await animate(
        scope.current,
        {
          rotate: 0,
          strokeDashoffset: offset1,
        },
        {
          duration: circleDuration * 0.25,
          ease: 'linear',
        }
      )

      await animate(
        scope.current,
        {
          rotate: 45,
          strokeDashoffset: offset2,
        },
        {
          duration: circleDuration * 0.25,
          ease: 'linear',
        }
      )

      await animate(
        scope.current,
        {
          rotate: 360,
          strokeDashoffset: offset1,
        },
        {
          duration: circleDuration * 0.25,
          ease: 'linear',
        }
      )

      await animate(
        scope.current,
        {
          rotate: 0,
          strokeDashoffset: offset1,
        },
        {
          duration: 0,
          ease: 'linear',
        }
      )

      await animateCircle()
    }

    animateCircle()
  }, [])
```

This is the `react-spring` counterpart. I wonder if this can be written more elegantly in framer. Not sure I am happy with the framer syntax.

```tsx
const circleSprings = useSpring({
    from: {
      transform: `rotate(0deg)`,
      strokeDashoffset: offset1,
    },
    to: [
      {
        transform: `rotate(45deg)`,
        strokeDashoffset: offset2,
        duration: circleSpringsDuration * 0.25,
        delay: circleSpringsDuration * 0.25,
      },
      {
        transform: `rotate(360deg)`,
        strokeDashoffset: offset1,
        duration: circleSpringsDuration * 0.25,
        delay: circleSpringsDuration * 0.25,
      },
    ],
    loop: true,
  })
```

**Comment by soosap** [comment]
After learning more about `useAnimation`, I found out that an animation sequence can be passed like this:

```tsx
      animate(
        [
          [scope.current, { rotate: 0, strokeDashoffset: offset1 }],
          [scope.current, { rotate: 45, strokeDashoffset: offset2 }],
          [scope.current, { rotate: 360, strokeDashoffset: offset1 }],
        ],
        {
          repeat: Infinity,
          defaultTransition: {
            ease: 'linear',
            duration: circleDuration * 0.25,
          },
        }
      )
```

It works, but unfortunately, a type error is being thrown:

```
utils.mjs:9 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at Object.test (utils.mjs:9:1)
    at Object.test (index.mjs:7:1)
    at getMixer (mix-complex.mjs:13:1)
    at mix-complex.mjs:25:1
    at Array.map (<anonymous>)
    at mixArray (mix-complex.mjs:25:1)
    at createMixers (interpolate.mjs:32:1)
    at interpolate (interpolate.mjs:74:1)
    at keyframes (keyframes.mjs:36:1)
```

**Comment by mattgperry** [comment]
Can you provide a sandbox of the TypeError please?

**Comment by soosap** [comment]
Hey there, I apologize, it was not really clear to me how to properly use sequential animations.

Doing it like this gives me the exact result that I want:

```tsx
animate(
      scope.current,
      {
        rotate: [0, 45, 360],
        strokeDashoffset: [offset1, offset2, offset1],
      },
      {
        ease: 'linear',
        times: [0, circleDuration * 0.25, circleDuration * 0.5],
        duration: circleDuration,
        repeat: Infinity
      }
    )
```

**Comment by nalnir** [comment]
@soosap I am facing the same problem. 

 const [scope, animate] = useAnimate()
 
   useEffect(() => {
    if (playerCardState.isPicked === cardIndex) {
         animate(scope.current, { z: 0.5 }, { duration: 1 })
    } else {
        animate(scope.current, { z: 0 }, { duration: 1 })
    }
  }, [playerCardState.isPicked])

return (
  <motion.group ref={scope}>
  ...
 </motion.group>
 
 I also tried with just regular <group> but the same error persists. Any idea why this is happening?
