### ISSUE TITLE
[BUG] Next link on Vercel error usign Framer-Motion

### ISSUE THREAD

**Issue by ViniciusCestarii** [framer/motion#2307]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

The bug is happening when this project using framer-motion is deployed on Vercel
When clicked on the Next links occurs a react error, using router too, but with just the tag <a> it works cause i think the problem is the way that next handle links

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
i dont have a CodeSanbox but i have the project deployed
https://simple-framer-motion-animations.vercel.app/

and the project repository
https://github.com/ViniciusCestarii/simpleFramerMotionAnimations

**4. Steps to reproduce**

1. use npx install react-next-app@latest
2. use npm install framer-motion 
3. create a  <AnimatePresence mode='wait'> wrapping all the children inside the body on layout
4. yarn dev and click in a Next link to the "server side error" occurs and this not helpful error from react:

596-d7b1750a604a1292.js:1 Error: Minified React error #482; visit https://reactjs.org/docs/error-decoder.html?invariant=482 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nb (fd9d1056-c2ad140a17e094a3.js:9:28724)
    at rm (fd9d1056-c2ad140a17e094a3.js:9:40141)
    at Object.rg [as use] (fd9d1056-c2ad140a17e094a3.js:9:40327)
    at t.use (596-d7b1750a604a1292.js:17:6738)
    at O (596-d7b1750a604a1292.js:1:20904)
    at ri (fd9d1056-c2ad140a17e094a3.js:9:38931)
    at im (fd9d1056-c2ad140a17e094a3.js:9:111695)
    at oM (fd9d1056-c2ad140a17e094a3.js:9:90039)
    at fd9d1056-c2ad140a17e094a3.js:9:89861
    at oT (fd9d1056-c2ad140a17e094a3.js:9:89868)

**5. Expected behavior**

Works fine

**6. Video or screenshots**

https://github.com/framer/motion/assets/124843824/94091912-af28-40a7-bf48-22bba8905e88

**7. Environment details**

I didnt touch any enviroment detail

**Comment by ViniciusCestarii** [comment]
Obs: i found out that the error is related to AnimatePresence  in RouteChangeAnimation 
'use client'
import { AnimatePresence, motion } from "framer-motion"
import { usePathname } from "next/navigation"
import { ReactNode } from "react"

interface RouteChangeAnimationProps {
  children: ReactNode
}

const RouteChangeAnimation = ({children}: RouteChangeAnimationProps) => {
  const pathname = usePathname()
  return (
    <AnimatePresence mode='wait'>
    <motion.div key={pathname}
    >
      {children}
      <motion.div
        className='absolute top-0 left-0 w-full h-screen from-transparent via-purple-800/95 to-purple-500/95 bg-gradient-to-t origin-bottom'
        initial={{ scaleY: 0, }}
        animate={{ scaleY: 0, }}
        exit={{ scaleY: 1, }}
        transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
      ></motion.div>
      <motion.div
        className='absolute top-0 left-0 w-full h-screen from-transparent via-purple-800/95 to-purple-500/95 bg-gradient-to-t origin-top'
        initial={{ scaleY: 1, }}
        animate={{ scaleY: 0, }}
        exit={{ scaleY: 0, }}
        transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
      ></motion.div>
    </motion.div>
  </AnimatePresence>
  )
}

export default RouteChangeAnimation
