### ISSUE TITLE
[BUG] "Component is not a function" when used with react-ssr-prepass

### ISSUE THREAD

**Issue by BjoernRave** [framer/motion#256]
**Describe the bug**

When creating a simple button like this: `<motion.button animate={{opacity: 1}}>Test</motion.button>` I get the following error: 

```shell
/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:546
      throw error;
      ^

TypeError: Component is not a function
    at renderWithHooks (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:271:18)
    at render$1 (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:543:12)
    at mount$1 (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:566:10)
    at render$3 (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:804:82)
    at visitElement (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:860:23)
    at visitLoop (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:912:22)
    at resumeVisitChildren (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:954:20)
    at Immediate.<anonymous> (/Users/bjoern/projects/CoolPlaces/frontend/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:978:9)
```

**To Reproduce**

I am using Next.js together with urql, so I also use react-ssr-prepass, which is probably causing the problem

To reproduce just take this example repo: https://github.com/FormidableLabs/urql/tree/master/examples/3-ssr-with-nextjs

install framer motion and create a basic button

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser firefox
 - Version: 1.4

**Comment by InventingWithMonster** [comment]
What version of React are you running?

**Comment by BjoernRave** [comment]
@kitten do you have any idea on how to fix this?

**Comment by kitten** [comment]
@BjoernRave What is your component there inheriting from? I assume if it's not a function it must be a class? Or is it something else like `forwardRef`?

If it's a class it shouldn't even be in `dispatcher` at that point since there's a separate case for class components:

- https://github.com/FormidableLabs/react-ssr-prepass/blob/03c94bf6e5dcba419dd647a0f936e272353f1318/src/visitor.js#L54-L64
- https://github.com/FormidableLabs/react-ssr-prepass/blob/03c94bf6e5dcba419dd647a0f936e272353f1318/src/element.js#L24-L25

If it's actually neither an element of a function or a class but a `ForwardRefElement` for instance, this could also be an issue with `react-is`.

**Comment by BjoernRave** [comment]
@kitten not sure what you mean, but it has nothing to do with my code, here is a  super basic codesandbox with the code from the next.js example and a basic framer-motion element: https://codesandbox.io/embed/hello-world-dpvnv

**Comment by InventingWithMonster** [comment]
@kitten the motion components are just functions wrapped in forwardRef. I can take a look into what react-is thinks it is, good pointer.

**Comment by kitten** [comment]
Hiya 👋  I pulled down the codesandbox locally and have found the issue in `react-ssr-prepass`. There's an open PR that'll fix this bug: https://github.com/FormidableLabs/react-ssr-prepass/pull/15

Specifically `react-ssr-prepass` was having trouble with this component, which is a `memo` component wrapping a `forwardRef` component: https://github.com/framer/motion/blob/b0dcfa8/src/motion/utils/use-motion-values.ts#L175

**Comment by InventingWithMonster** [comment]
@kitten thanks for taking a look!

**Comment by BjoernRave** [comment]
thank you two for fixing this problem. I am looking forward to use framer-motion all over my project very soon :D
