### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'animate')

### ISSUE THREAD

**Issue by cpojer** [framer/motion#2564]
Following up on https://github.com/framer/motion/issues/2558, I updated to 11.0.14 and immediately saw production crashes again:

![CleanShot 2024-03-17 at 10 54 03@2x](https://github.com/framer/motion/assets/13352/bf4cad7d-f2f7-4b42-a226-842e0c34f678)

I immediately reverted the change and I'm running 11.0.8 again. It appears there is still a regression in the latest patch releases.

**Comment by eltmon** [comment]
I am also having the same issue specifically with 11.0.14:

Uncaught TypeError: Cannot read properties of null (reading 'animate')
    at animateStyle (index.mjs:13:20)
    at AcceleratedAnimation.initPlayback (AcceleratedAnimation.mjs:98:27)
    at AcceleratedAnimation.onKeyframesResolved (BaseAnimation.mjs:59:21)
    at DOMKeyframesResolver.onComplete (AcceleratedAnimation.mjs:81:104)
    at DOMKeyframesResolver.complete (KeyframesResolver.mjs:129:14)
    at KeyframesResolver.mjs:27:46
    at Set.forEach (<anonymous>)
    at measureAllKeyframes (KeyframesResolver.mjs:27:15)
    at flushKeyframeResolvers (KeyframesResolver.mjs:40:5)
    at get resolved (BaseAnimation.mjs:28:13)

**Comment by eltmon** [comment]
Confirming I am still getting this on 11.0.14:

index.mjs:13 Uncaught TypeError: Cannot read properties of null (reading 'animate')
    at animateStyle (index.mjs:13:20)
    at AcceleratedAnimation.initPlayback (AcceleratedAnimation.mjs:98:27)
    at AcceleratedAnimation.onKeyframesResolved (BaseAnimation.mjs:59:21)
    at DOMKeyframesResolver.onComplete (AcceleratedAnimation.mjs:81:104)
    at DOMKeyframesResolver.complete (KeyframesResolver.mjs:129:14)
    at KeyframesResolver.mjs:27:46
    at Set.forEach (<anonymous>)
    at measureAllKeyframes (KeyframesResolver.mjs:27:15)
    at flushKeyframeResolvers (KeyframesResolver.mjs:40:5)
    at get resolved (BaseAnimation.mjs:28:13)

**Comment by mattgperry** [comment]
Closing this as fixed as this should be fixed in latest versions. But if you find it isn't fixed please open a new ticket with a sandbox.
