### ISSUE TITLE
[BUG] ReferenceError: React is not defined Just by importing framer-motion

### ISSUE THREAD

**Issue by juanboterotech** [framer/motion#2627]
I'm started to work with a React project which uses framer to animate elements in sidebar after login screen, but it is causing console error when importing: `Uncaught ReferenceError: React is not defined`

I tested just by importing the library in login component, without using the library and is causing me the same behavior.

I try to import like this: `import { AnimatePresence, motion } from "framer-motion/dist/framer-motion";`
The web site is just a blank screen, the console show this:

`
Uncaught ReferenceError: React is not defined
    at framer-motion.js:1:1
    at framer-motion.js:1:1
    at ./node_modules/framer-motion/dist/framer-motion.js (framer-motion.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:150:1)
    at ./src/modules/auth/components/login-form/LoginForm.jsx (LoginForm.css:45:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:150:1)
    at ./src/modules/auth/components/login/Login.jsx (LoginForm.jsx:125:1) **End of file**
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:150:1)
    at ./src/modules/auth/AuthModule.jsx (index.js:9:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:150:1)
    at ./src/App.js (App.css:45:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:150:1)
    at ./src/index.js (index.css:45:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:150:1)
    at 1 (useAuth.jsx:9:1)
    at __webpack_require__ (bootstrap:789:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:69
`
In package.json i'm using versión 11.1.3
`"framer-motion": "^11.1.3",`

**Steps to reproduce**

1. Go to any component and import framer-motion lib
2. Refresh the browser page
3. See error in console

**Expected behavior**

Components and elements load

**6. Video or screenshots**
![image](https://github.com/framer/motion/assets/63695358/3fd91b51-94b4-40c0-a684-ec03c8cccdf1)

Tested with Chrome, Edge with same result

**Comment by mattgperry** [comment]
Why aren't you importing 

```
import { AnimatePresence, motion } from "framer-motion"
```

**Comment by juanboterotech** [comment]
> Why aren't you importing
> 
> ```
> import { AnimatePresence, motion } from "framer-motion"
> ```

when I Try in that way i got this error in terminal.
```
Failed to compile.

./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

**Comment by mattgperry** [comment]
Could you be running into this: https://github.com/framer/motion/issues/1525#issuecomment-1177081896

**Comment by hippo-m** [comment]
I solved this issue by adding a Webpack rule.

If you’re using react-app-rewired, add the following to your config-overrides.js file:
`addWebpackModuleRule({
  test: /\.mjs$/,
  include: /node_modules/,
  type: "javascript/auto"
});`

If you’re using Webpack directly, include this rule in your webpack.config.js:
`module: {
  rules: [
    {
      test: /\.mjs$/,
      include: /node_modules/,
      type: "javascript/auto"
    }
  ]
}`
This ensures that .mjs files are correctly handled by Webpack.

**Comment by mahmutisci** [comment]
I solved this issue by adding a Webpack rule.

If you’re using react-app-rewired, add the following to your config-overrides.js file:
`addWebpackModuleRule({
  test: /\.mjs$/,
  include: /node_modules/,
  type: "javascript/auto"
});`

If you’re using Webpack directly, include this rule in your webpack.config.js:
`module: {
  rules: [
    {
      test: /\.mjs$/,
      include: /node_modules/,
      type: "javascript/auto"
    }
  ]
}`
This ensures that .mjs files are correctly handled by Webpack.
