### ISSUE TITLE
[BUG] Docs: Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Nozomi-Hijikata** [framer/motion#2628]
## **1.  Description of the bug**
When I visit the introduction page of Framer motion, an application error has occurred.
How should I handle this?

The message shown in the screen below.
```
Application error: a client-side exception has occurred (see the browser console for more information).
```
The browser console message is attached in Section 5 below.

## **2. Steps to reproduce**

1. Open [the introduction page](https://www.framer.com/motion/introduction/) in the browser.

###  Chrome
<img width="1512" alt="スクリーンショット 2024-04-18 12 12 47" src="https://github.com/framer/motion/assets/116155762/ef12d745-11fe-476a-b6e6-d1634029cab0">

### Safari
<img width="1317" alt="スクリーンショット 2024-04-18 12 14 30" src="https://github.com/framer/motion/assets/116155762/7e7c758a-b6eb-438f-b3be-6b5de79b907b">

## **4. Environment details**
macOS Sonoma ver14.3.1
Chrome(ver. 124.0.6367.62(Official Build)(arm64)) (even after cache were deleted)
Safari(ver. 17.3.1 (19617.2.4.11.12))

## **5. Detail log**
As I follow the instruction in the screen, the message attached below is displayed.
```
19Third-party cookie will be blocked. Learn more in the Issues tab.
api.framer.com/site/users/me:1 
        
 Failed to load resource: the server responded with a status of 401 ()
client:49 [GSI_LOGGER]: Your client application may not display the Google One Tap in its default position. When FedCM becomes mandatory, One Tap only displays in the default position. Refer to the migration guide to update your code accordingly and opt-in to FedCM to test your changes. Learn more: https://developers.google.com/identity/gsi/web/guides/fedcm-migration?s=dc#layout
_.y @ client:49
client:49 [GSI_LOGGER]: Your client application uses one of the Google One Tap prompt UI status methods that may stop functioning when FedCM becomes mandatory. Refer to the migration guide to update your code accordingly and opt-in to FedCM to test your changes. Learn more: https://developers.google.com/identity/gsi/web/guides/fedcm-migration?s=dc#display_moment and https://developers.google.com/identity/gsi/web/guides/fedcm-migration?s=dc#skipped_moment
_.y @ client:49
examples/:1 Third-party sign in was disabled in browser Site Settings.
api.framer.com/auth/signin:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
api.framer.com/site/users/me:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
client:50 [GSI_LOGGER]: FedCM get() rejects with AbortError: signal is aborted without reason
_.z @ client:50
examples/:1 Third-party sign in was disabled in browser Site Settings.
framework-336caa3f6419768205fe.js:1 TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
at [slug]-eefd1fea1566058c1e89.js:1:14699
at Ii (framework-336caa3f6419768205fe.js:1:105602)
at t.unstable_runWithPriority (framework-336caa3f6419768205fe.js:1:130401)
at Wl (framework-336caa3f6419768205fe.js:1:45773)
at Oi (framework-336caa3f6419768205fe.js:1:105063)
at framework-336caa3f6419768205fe.js:1:104974
at D (framework-336caa3f6419768205fe.js:1:129460)
at w.port1.onmessage (framework-336caa3f6419768205fe.js:1:128182)
uu @ framework-336caa3f6419768205fe.js:1
main-a3d202dbe74dc08b5ac7.js:1 TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
at [slug]-eefd1fea1566058c1e89.js:1:14699
at Ii (framework-336caa3f6419768205fe.js:1:105602)
at t.unstable_runWithPriority (framework-336caa3f6419768205fe.js:1:130401)
at Wl (framework-336caa3f6419768205fe.js:1:45773)
at Oi (framework-336caa3f6419768205fe.js:1:105063)
at framework-336caa3f6419768205fe.js:1:104974
at D (framework-336caa3f6419768205fe.js:1:129460)
at w.port1.onmessage (framework-336caa3f6419768205fe.js:1:128182)
le @ main-a3d202dbe74dc08b5ac7.js:1
main-a3d202dbe74dc08b5ac7.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
le @ main-a3d202dbe74dc08b5ac7.js:1
api.framer.com/auth/signin:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
api.framer.com/site/users/me:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
client:50 [GSI_LOGGER]: FedCM get() rejects with AbortError: signal is aborted without reason
_.z @ client:50
introduction/:1 Third-party sign in was disabled in browser Site Settings.
client:50 [GSI_LOGGER]: FedCM get() rejects with NetworkError: Error retrieving a token.
```

**Comment by mattgperry** [comment]
Thanks for the heads-up, we're gonna take a look

**Comment by Nozomi-Hijikata** [comment]
@mattgperry 
I will close this issue, because It seems it was already fixed.
Thank you for your time!
