### ISSUE TITLE
[BUG] Motion custom component throw error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by fukemy** [framer/motion#2777]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I have work with motion + NextUI, I want to create motion component from Button, but I got the error when run it:
```
render.mjs:6 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at HTMLVisualElement.renderHTML [as renderInstance] (render.mjs:6:12)
    at VisualElement.render (VisualElement.mjs:141:18)
    at triggerCallback (render-step.mjs:32:9)
    at Set.forEach (<anonymous>)
    at Object.process (render-step.mjs:73:23)
    at processBatch (batcher.mjs:49:16)
``` 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

```
import { Button } from "@nextui-org/react"
import { motion } from "framer-motion"
import React from "react"

const AnimateButton = React.forwardRef((props, ref) => (
    <Button ref={ref} {...props} />
))

export const MotionButton = motion(AnimateButton)
```

Here is how I used:
```
<MotionButton size="lg" rounded
                    color="gradient" auto ghost={false}
                    // onPress={onBuyPackageClick}
                    shadow>
                    {/* {buttonLoading ? <Loading color="currentColor" size="sm" /> : "Buy"} */} BUY BUY
                </MotionButton>
```

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

1. install nextui + motion
2. copy above code
3. Run project

**Comment by jakeleboeuf** [comment]
I'm running into the same issue. I setup a minimal codesandbox to repro if it's helpful.

I _can_ still import `m` from the main entry without issues, and am handling the `use client` directive in my own build step. Moving to the new entry might not be necessary for my use case unless the plan is to deprecate that import path and move entirely to `framer-motion/m` 👀 

### Codesandbox reproductions
- [x] [Working](https://codesandbox.io/p/sandbox/main-entry-framer-motion-custom-component-11-3-30-5fmghs) with 11.3.30
- [x] [Working](https://codesandbox.io/p/sandbox/main-entry-framer-motion-custom-component-11-4-0-cqmr2p) with main entry (11.3.30)
- [ ] [Not working](https://codesandbox.io/p/sandbox/m-entry-framer-motion-custom-component-11-4-0-q4lwlg) with 11.4.0
